/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jordi_pruebafacebook2017sdk1_MainActivity */

#ifndef _Included_org_jordi_pruebafacebook2017sdk1_MainActivity
#define _Included_org_jordi_pruebafacebook2017sdk1_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jordi_pruebafacebook2017sdk1_MainActivity
 * Method:    convertirGrises
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_org_jordi_pruebafacebook2017sdk1_MainActivity_convertirGrises
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_jordi_pruebafacebook2017sdk1_MainActivity
 * Method:    convertirSepia
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_org_jordi_pruebafacebook2017sdk1_MainActivity_convertirSepia
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_jordi_pruebafacebook2017sdk1_MainActivity
 * Method:    creaMarco
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_org_jordi_pruebafacebook2017sdk1_MainActivity_creaMarco
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_jordi_pruebafacebook2017sdk1_MainActivity
 * Method:    creaMarcoCallBack
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_org_jordi_pruebafacebook2017sdk1_MainActivity_creaMarcoCallBack
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
